export enum Actions {
  OPEN_MODAL = "OPEN_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
  ADD_LOCATION = "ADD_LOCATION",
  EDIT_LOCATION = "EDIT_LOCATION",
  REMOVE_LOCATION = "REMOVE_LOCATION",
  CHANGE_STATUS = "CHANGE_STATUS",
}
